version: "0"

services:
  qlever:
    image: niklas88/qlever
    volumes:
      - ./index:/index
    environment:
      - INDEX_PREFIX=scientists-index
    depends_on:
      - build_index
    command: "-t -a"

steps:
  download_input:
    image: busybox
    volumes:
      - ./input:/input
    command:
      "wget -P /input/ http://filicudi.informatik.uni-freiburg.de/bjoern-data/scientist-collection.zip"

  unzip_input:
    after:
      - download_input
    image: busybox
    volumes:
      - ./input:/input
    command:
      "unzip -d /input /input/scientist-collection.zip"

  build_index:
    after:
      - unzip_input
    image: niklas88/qlever
    volumes:
      - ./input/scientist-collection:/input:ro
      - ./index:/index
    entrypoint: "IndexBuilderMain"
    command: "-a -l -i /index/scientists-index -n /input/scientists.nt -w /input/scientists.wordsfile.tsv -d /input/scientists.docsfile.tsv"

  wait_for_qlever:
    after:
      - qlever
    build:
      context: ./waitfor
    command: "waitfor http://qlever:7001"

  run_queries:
    after:
      - wait_for_qlever
    image: niklas88/qlever
    volumes:
      - ./tests:/tests
    entrypoint: python3
    command: "/app/e2e/queryit.py /app/e2e/scientists_queries.yaml http://qlever:7001"

  clean:
    after:
      - run_queries
    volumes:
      - ./input:/input
      - ./index:/index
    image: busybox
    entrypoint: "sh -c"
    # "'" so we pass the whole command as one argument to sh -c
    command: "'rm -rf /input/* /index/*'"

